### ISSUE TITLE
Buttons less visible on smaller resolutions

### ISSUE THREAD

**Issue by ibombonato** [KartikChugh/Otto#18]
The "next step" button is hidden behind the chatbot depending on screen size, so it may affect the usability.

![image](https://user-images.githubusercontent.com/1737342/88701077-eebefd80-d0df-11ea-9e68-7039871c1c82.png)

**Comment by KartikChugh** [comment]
As the web app was developed in roughly a month for the hackathon, it was primarily tested for a 1080p resolution.
Adjusting for different resolutions is definitely a priority. 
Thanks!

**Comment by renesansz** [comment]
I also have the same issue the chat popup is blocking the view especially on the next steps when you choose which dataset you want to use.

**Comment by KartikChugh** [comment]
We're working on this! In the meantime, note that it works fine on 1920×1080 resolutions, which you can switch to if you'd still like to try out the app

**Comment by sanujb** [comment]
Fixed!
