### ISSUE TITLE
You can't see the descriptions of the options

### ISSUE THREAD

**Issue by JLP04** [KartikChugh/Otto#19]
On your website, I can't see the descriptions of the options. I am including a screenshot to better describe my issue. 
[Screen Shot 2020-07-30 at 9.25.55 AM.pdf](https://github.com/KartikChugh/Otto/files/5001471/Screen.Shot.2020-07-30.at.9.25.55.AM.pdf)

**Comment by KartikChugh** [comment]
We have the issue being tracked here: https://github.com/KartikChugh/Otto/issues/18
